// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgjruTE1LZsjHLlxcQLqKvIUGi5ei0ug',
    appId: '1:426164924838:web:9a8dcae3585e96dc395f67',
    messagingSenderId: '426164924838',
    projectId: 'union-3c208',
    authDomain: 'union-3c208.firebaseapp.com',
    storageBucket: 'union-3c208.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvN6zsarD-CTri9v3gXqmhEGrVjUc2oo',
    appId: '1:426164924838:android:a9501c8badb4a90c395f67',
    messagingSenderId: '426164924838',
    projectId: 'union-3c208',
    storageBucket: 'union-3c208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAtPhAu0wFcSkaFwb5qjTiKnUYkUPl_oM',
    appId: '1:426164924838:ios:5368ae8e91137e62395f67',
    messagingSenderId: '426164924838',
    projectId: 'union-3c208',
    storageBucket: 'union-3c208.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAtPhAu0wFcSkaFwb5qjTiKnUYkUPl_oM',
    appId: '1:426164924838:ios:5368ae8e91137e62395f67',
    messagingSenderId: '426164924838',
    projectId: 'union-3c208',
    storageBucket: 'union-3c208.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlgjruTE1LZsjHLlxcQLqKvIUGi5ei0ug',
    appId: '1:426164924838:web:b562a47a04292819395f67',
    messagingSenderId: '426164924838',
    projectId: 'union-3c208',
    authDomain: 'union-3c208.firebaseapp.com',
    storageBucket: 'union-3c208.firebasestorage.app',
  );

}